from . import platform_config
from . import payroll_settings
from . import salary_import
from . import salary_import_line
from . import employee_ledger
from . import commission_receipt
from . import truck
from . import truck_trip
from . import employee_cost
from . import manpower_contract
from . import manpower_timesheet
from . import manpower_project_expense
from . import fleet_vehicle_extension
from . import access_control
from . import fleet_service_extension
from . import partner_extension
from . import client_po
from . import equipment_rental
from . import equipment_rental_inbound
# ── New features (BRD v2) ────────────────────────────────────────────────────
from . import entry_category
from . import installment_schedule
from . import asset_register
from . import account_move_extension
from . import cashflow_alert
